### ISSUE TITLE
大佬这个是什么问题。

### ISSUE THREAD

**Issue by duoshoumiao** [aJacke/pcr-wiki-pyppeteer-rebuild#2]
![dadf3ef3d3e368d91729e089e4eed25e](https://github.com/user-attachments/assets/c3c99fb0-4f36-4ae5-b986-2f4e5029781e)

**Comment by duoshoumiao** [comment]
pyppeteer==1.0.2 解决了

**Comment by duoshoumiao** [comment]
PS C:\Resources\img\priconne\spider> python run.py
Traceback (most recent call last):
  File "run.py", line 105, in <module>
    asyncio.get_event_loop().run_until_complete(main())
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python38\lib\asyncio\base_events.py", line 616, in run_until_complete
    return future.result()
  File "run.py", line 96, in main
    await chara_data(page, idx, name)
  File "C:\Resources\img\priconne\spider\Fetch.py", line 173, in chara_data
    introduce = await get_chara_data(page, "簡介", name, 'introduce')
  File "C:\Resources\img\priconne\spider\Fetch.py", line 39, in get_chara_data
    introduce = await page.evaluate('(element) => element.innerText', element[0])
IndexError: list index out of range
PS C:\Resources\img\priconne\spider>

**Comment by duoshoumiao** [comment]
PS I:\pcr-wiki-pyppeteer-rebuild-master\spider> python run.py
Error: No elements found for 日和（公主） (infoelem) with selector 屬性
Error: No elements found for 日和（公主） (guild) with selector 公會
Error: No elements found for 日和（公主） (birthday) with selector 生日
Error: No elements found for 日和（公主） (age) with selector 年齡
Error: No elements found for 日和（公主） (height) with selector 身高
Error: No elements found for 日和（公主） (weight) with selector 體重
Error: No elements found for 日和（公主） (blood_type) with selector 血型
Error: No elements found for 日和（公主） (race) with selector 種族
Error: No elements found for 日和（公主） (hobby) with selector 喜好
Error: No elements found for 日和（公主） (cv) with selector 聲優
Error: No elements found for 日和（公主） (introduce) with selector 簡介
Element with '起手' not found
Element with '循環' not found
Traceback (most recent call last):
  File "run.py", line 105, in <module>
    asyncio.get_event_loop().run_until_complete(main())
  File "C:\Users\laibao\AppData\Local\Programs\Python\Python38\lib\asyncio\base_events.py", line 616, in run_until_complete
    return future.result()
  File "run.py", line 96, in main
    await chara_data(page, idx, name)
  File "I:\pcr-wiki-pyppeteer-rebuild-master\spider\Fetch.py", line 190, in chara_data
    month, day = birthday.split(" / ")
AttributeError: 'NoneType' object has no attribute 'split'

**Comment by duoshoumiao** [comment]
浏览器替换成谷歌最新的就好了

**Comment by duoshoumiao** [comment]
![Screenshot_2024-10-19-15-05-44-81_22d2f3c2df26fdc9c879008859bd486f.jpg](https://github.com/user-attachments/assets/57f36539-81ce-4016-823e-4c1843d45e87)

我又来了，为什么简介爬不了了
